# Generated by Django 4.2.2 on 2023-06-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_userprofile_email_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_image',
            field=models.ImageField(upload_to='user_app/profile_pics'),
        ),
    ]
