# Generated by Django 4.2.2 on 2023-07-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0003_userprofile_groups_userprofile_user_permissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="experience_image",
            field=models.ImageField(blank=True, null=True, upload_to="experience_pics"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="experience_tags",
            field=models.ManyToManyField(
                blank=True, null=True, to="user_app.experiencetag"
            ),
        ),
    ]
