# Generated by Django 4.2.2 on 2023-07-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0004_alter_experience_experience_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_bio",
            field=models.TextField(default="Insert bio"),
        ),
    ]