# Generated by Django 4.2.2 on 2023-07-11 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0003_alter_experience_experience_image_and_more"),
        ("user_app", "0005_userprofile_user_bio"),
    ]

    operations = []
