# Generated by Django 4.2.2 on 2023-07-14 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0005_userprofile_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="experience",
            name="region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_app.region",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
