# Generated by Django 4.2.2 on 2023-07-14 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0006_experience_end_date_experience_region_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="region",
            field=models.ForeignKey(
                default="default-region",
                on_delete=django.db.models.deletion.CASCADE,
                to="user_app.region",
            ),
        ),
    ]
