# Generated by Django 4.2.2 on 2023-07-14 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0008_alter_experience_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_app.region",
            ),
        ),
    ]
