# Generated by Django 4.2.2 on 2023-07-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_bio',
            field=models.TextField(default='Insert bio'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_image',
            field=models.ImageField(blank=True, null=True, upload_to='experience_pics'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_tags',
            field=models.ManyToManyField(blank=True, null=True, to='user_app.experiencetag'),
        ),
    ]
