# Generated by Django 4.2.2 on 2023-07-04 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0008_experience_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="experience",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="region",
            name="region_desc",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
