# Generated by Django 4.2.2 on 2023-07-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_userprofile_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='old_user', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='someone', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='someone', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='dummy_user', max_length=250, unique=True),
        ),
    ]
