# Generated by Django 4.2.2 on 2023-07-21 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0009_alter_experience_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="traveler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_app.userprofile"
            ),
        ),
    ]
