<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-08-08 13:22
=======
# Generated by Django 4.2.2 on 2023-08-08 13:54
>>>>>>> b025ee0147aaa84a9c2e8d626a3cc4e426e1963b

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('user_app', '0019_alter_userprofile_user_profile_image'),
=======
    dependencies = [
        ("user_app", "0019_alter_userprofile_user_profile_image"),
>>>>>>> b025ee0147aaa84a9c2e8d626a3cc4e426e1963b
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='userprofile',
            name='user_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_app/profile_pics'),
=======
            model_name="userprofile",
            name="user_profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="user_app/profile_pics"
            ),
>>>>>>> b025ee0147aaa84a9c2e8d626a3cc4e426e1963b
        ),
    ]
