# Generated by Django 4.2.2 on 2023-08-04 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0010_alter_booking_traveler_alter_review_author"),
        ("user_app", "0019_alter_userprofile_user_profile_image"),
    ]

    operations = []
