# Generated by Django 4.2.2 on 2023-08-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_alter_userprofile_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_app/profile_pics'),
        ),
    ]
