# Generated by Django 4.2.2 on 2023-07-18 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("match_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
