# Generated by Django 4.2.2 on 2023-07-05 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.RemoveField(
            model_name="postaudio",
            name="post",
        ),
        migrations.RemoveField(
            model_name="postfile",
            name="post",
        ),
        migrations.RemoveField(
            model_name="postimage",
            name="post",
        ),
        migrations.RemoveField(
            model_name="postlink",
            name="post",
        ),
        migrations.RemoveField(
            model_name="postpoll",
            name="post",
        ),
        migrations.RemoveField(
            model_name="postpollvote",
            name="post_poll",
        ),
        migrations.RemoveField(
            model_name="postvideo",
            name="post",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="PostAudio",
        ),
        migrations.DeleteModel(
            name="PostFile",
        ),
        migrations.DeleteModel(
            name="PostImage",
        ),
        migrations.DeleteModel(
            name="PostLink",
        ),
        migrations.DeleteModel(
            name="PostPoll",
        ),
        migrations.DeleteModel(
            name="PostPollVote",
        ),
        migrations.DeleteModel(
            name="PostVideo",
        ),
    ]
