# Generated by Django 4.2.2 on 2023-07-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("traveler", models.CharField(max_length=50)),
                ("host", models.CharField(max_length=50)),
                ("experience_name", models.CharField(max_length=200)),
            ],
        ),
    ]
