# Generated by Django 4.2.2 on 2023-07-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_continent_mpoly_country_mpoly_offer_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='country',
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
